services:
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ce:alpine'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data:/data'
    ports:
      - 9443:9443
      #- 8000:8000  # Remove if you do not intend to use Edge Agents   

networks:
  default:
    name: homelab_network
